version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: monthly
      timezone: Asia/Hong_Kong
      day: thursday
      time: "15:00"
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: pub
    schedule:
      timezone: Asia/Hong_Kong
      interval: monthly
      time: "15:00"
      day: monday
      
