name: device_vendor_info
description: Get hardware information (BIOS, Motherboard and System) into Flutter platform.
version: 3.0.0
homepage: https://github.com/rk0cc/device_vendor_info
funding:
  - https://github.com/sponsors/rk0cc
topics:
  - hardware
  - device
  - bios
environment: 
  sdk: ^3.10.0
resolution: workspace
dependencies:
  meta: ^1.17.0
  device_vendor_info_interface: ^5.1.1
  device_vendor_info_unix: ^3.0.0
  device_vendor_info_windows: ^3.0.0
dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
platforms:
  linux:
  macos:
  windows: 
