name: device_vendor_info_vmchecker
description: Virtual platform detection plugin for device_vendor_info packages
version: 2.0.0
homepage: https://github.com/rk0cc/device_vendor_info
repository: https://github.com/rk0cc/device_vendor_info/tree/main/vmchecker
environment:
  sdk: ^3.10.0
resolution: workspace
dependencies: 
  code_assets: ^1.0.0
  hooks: ^1.0.0
  native_toolchain_c: ">=0.17.6 <1.0.0"
  ffi: ^2.2.0
dev_dependencies:
  lints: ^6.1.0
  ffigen: ^20.1.1
hook:
  build: true
