// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Bool Function()>(
	assetId: 'package:device_vendor_info_vmchecker/device_vendor_info_vmchecker.dart',
)
external bool is_hypervisor();
