name: Bundle action
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bundle.yml'
      - 'bundle/**.dart'
jobs:
  unittest:
    name: Flutter unit test
    env:
      working-directory: './bundle'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.x'
      - name: Get dependencies
        working-directory: ${{ env.working-directory }}
        run: flutter pub get
      - name: Perform test
        working-directory: ${{ env.working-directory }}
        run: flutter test .
  
